<?php

namespace AppBundle\Repository;

/**
 * HashRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashRepository extends \Doctrine\ORM\EntityRepository
{
}
