imports:
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator:
        paths:
#            - '%kernel.project_dir%/app/Resources/translations'
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    globals:
        app_name: '%app_name%'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        dql:
            string_functions:
                MONTH: DoctrineExtensions\Query\Mysql\Month
                YEAR: DoctrineExtensions\Query\Mysql\Year
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

#monolog:
#    handlers:
#        main:
#            type: stream
#            path: '%kernel.logs_dir%/customlogs.log'
#            level: info

easy_admin:
    entities:
        # change the following to the namespaces of your own entities
        Product:
            class:  AppBundle\Entity\Product
            list:
                actions: ["edit", "delete", "show"]
            form:
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'cost', label: 'Cost' }

        Customer:
            class:  AppBundle\Entity\Customer
            form:
                fields:  ["name", "address"]
            list:
                actions: ["edit", "delete", "show"]
                fields:  ["id", "name", "address", "dateTime"]
        Orders:
            class:  AppBundle\Entity\Orders
            form:
                fields:
                    - { property: 'user', label: 'UserId' }
                    - { property: 'name', label: 'OrderName' }
                    - { property: 'services', label: 'Services' }
                    - { property: 'products', label: 'Products' }
            list:
                actions: ["edit", "delete", "show", "invoice"]
        Service:
            class:  AppBundle\Entity\Service
            list:
                actions: ["edit", "delete", "show"]
            form:
                fields:
                    - { property: 'name', label: 'Name' }
                    - { property: 'price', label: 'Price' }
        PendingOrder:
            class:  AppBundle\Entity\Orders
            list:
                dql_filter: 'entity.isAccepted = false'
                actions: ["edit", "delete", "show"]
            form:
                fields:
                    - { property: 'user', label: 'UserId' }
                    - { property: 'name', label: 'OrderName' }
                    - { property: 'services', label: 'Services' }
                    - { property: 'products', label: 'Products' }
        AcceptedOrder:
            class:  AppBundle\Entity\Orders
            list:
                dql_filter: 'entity.isAccepted = true'
                actions: ["edit", "delete", "show"]
            form:
                fields:
                    - { property: 'user', label: 'UserId' }
                    - { property: 'name', label: 'OrderName' }
                    - { property: 'services', label: 'Services' }
                    - { property: 'products', label: 'Products' }
        Sales:
            class:  AppBundle\Entity\Sales
            disabled_actions: ['delete', "edit", "new"]












