product_routing_file:
    # loads routes from the given routing file stored in some bundle
    resource: 'product_routing.yml'
    prefix: /product
app:
    resource: '@AppBundle/Controller/'
    type: annotation
app_product:
    resource: '@AppBundle/Controller/ProductController.php'
    type: annotation
    prefix: '/product'
url:
    path:     /lucky/url
    defaults: { _controller: AppBundle:Lucky:getURL }
fun:
    path:     /lucky/fun/{str}
    defaults: { _controller: AppBundle:Lucky:fun, str: "hash"}
