app:
    resource: '@AppBundle/Controller/'
    type: annotation
app_product:
    resource: '@AppBundle/Controller/ProductController.php'
    type: annotation
    prefix: '/product'
url:
    path:     /lucky/url
    defaults: { _controller: AppBundle:Lucky:getURL }
fun:
    path:     /lucky/fun/{str}
    defaults: { _controller: AppBundle:Lucky:fun, str: "hash"}
