app:
    resource: '@AppBundle/Controller/'
    type: annotation
    #prefix:   /admin
url:
    path:     /lucky/url
    defaults: { _controller: AppBundle:Lucky:getURL }
fun:
    path:     /lucky/fun/{str}
    defaults: { _controller: AppBundle:Lucky:fun, str: "hash"}
